# Generated by Django 5.1.2 on 2024-10-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_discussions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='discussion_likes',
            field=models.IntegerField(default=0),
        ),
    ]
