# Generated by Django 5.1.2 on 2024-10-18 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_discussions', '0002_discussion_discussion_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Text of the comment')),
                ('comment_likes', models.IntegerField(default=0)),
                ('comment_time', models.DateTimeField()),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('commented_discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='all_discussions.discussion')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
