# Generated by Django 5.1.2 on 2024-10-18 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_discussions', '0005_alter_comment_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 0, 4, 14, 711497)),
        ),
    ]
