# Generated by Django 5.1.2 on 2024-10-20 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_discussions', '0007_alter_comment_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_surprised_reactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 15, 41, 48, 898220)),
        ),
    ]
