# Generated by Django 5.1.2 on 2024-10-20 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_discussions', '0008_comment_comment_surprised_reactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_surprised_reactions',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_reactions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 17, 22, 50, 276629)),
        ),
    ]
