# Generated by Django 5.1.2 on 2024-10-21 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_discussions', '0011_remove_discussion_discussion_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 16, 6, 55, 16326)),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='discussion_reactions',
            field=models.JSONField(default={}),
        ),
    ]
