# Generated by Django 5.1.2 on 2024-10-23 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_discussions', '0013_alter_comment_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 20, 58, 18, 662924)),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='discussion_reactions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='subject_name',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
    ]
