# Generated by Django 5.1.2 on 2024-10-23 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_discussions', '0014_alter_comment_comment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 21, 1, 1, 738595)),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='last_comment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
