# Generated by Django 5.1.2 on 2024-10-27 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_discussions', '0017_rename_last_comment_time_discussion_discussion_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_reactions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 12, 47, 0, 734928)),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='discussion_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 12, 47, 0, 734928)),
        ),
    ]
